### ISSUE TITLE
Dispatching an action after update causes crash

### ISSUE THREAD

**Issue by V1rus999** [zendesk/Suas-Android#42]
Logical Steps -

When user clicks on an item we send the action to the store, the store then sends the action to the RoutingReducer which will update the routing state and update the main activity with the new state. The mainActivity will then route to the new activity and let the store know that it has routed and the routing state needs to be set back to none

```
    override fun update(state: CurrentRoutingState) {
        if (state.routingState is RoutingState.RouteToInbox) {
            TaskFormActivity.start(this, (state.routingState as RoutingState.RouteToInbox).id)
            store.dispatch(DetailLoaded)
        }
    }
```

When doing it like above, we get a `throw new RuntimeException("You must not dispatch actions in your reducer. Seriously. (╯°□°）╯︵ ┻━┻");`

Issue : 

We are not dispatching actions in the reducer. This should not happen. This is a breaking issue and it basically means we are not allowed to do actions in quick succession inside the update function. 

The following code fixes the error on our side but it is not ideal and the Suas store should handle the action queue internally: 

```    override fun update(state: CurrentRoutingState) {
        if (state.routingState is RoutingState.RouteToInbox) {
            TaskFormActivity.start(this, (state.routingState as RoutingState.RouteToInbox).id)
            Handler().postDelayed({ store.dispatch(DetailLoaded) }, 50)
        }
    }
```

Expected behaviour : 

No exception. The following code inside the SuasStore's dispatch() method should work better and perhaps add new actions to a queue `notifyListener(oldState, getState(), result.getUpdatedKeys()); isReducing.set(false);` 

This is a breaking issue and we cannot continue using the library with this issue still in.

Further info : 

None of our reducers dispatch actions, they are all pure classes/methods.

**Comment by schlan** [comment]
This should be fixed in v1.1.0
